drivers:
    s3:
        default:
            profile: default
            bucket: <bucket_name>
            url: <endpoint_url>
            path: <path_on_bucket>
    fs:
        default:
            output_path: /tmp/backup

jobs: []